### ISSUE TITLE
Add theme settings to a ThemeData widget

### ISSUE THREAD

**Issue by akshansh2000** [akshansh2000/learn_ar_flutter#3]
Currently, all the theme settings like background color, text color, etc. are hard-coded.

If one wants to change a certain color/accent, he/she would have to change it at various places.

Add a `ThemeData` widget to the app, having the theming settings saved in it.

**Comment by NesaByte** [comment]
Hi there! I want to do this, please assign this to me.

**Comment by NesaByte** [comment]
Thank you so much for assigning this to me. I requested a PR please check it out and see if there's anything I need to change, Thank you so much!
